Add default_content_type setting in Japanese readme
sinatra/sinatra pull request #1650
Opened 2020-10-06 14:28 UTC by decoch

I translated this  commit. https://github.com/sinatra/sinatra/commit/2128dcfb31f0e067bfc8e28afd54b94021caee68#diff-04c6e90faac2675aa89e2176d2eec7d8

2020-11-04 17:38 UTC, namusyaka requested changes
@decoch I'm sorry for the late reply. Thanks for your first contribution.
I've just reviewed and left some comments. PTAL.

2020-11-04 17:38 UTC, namusyaka commented on README.ja.md
> +    不明なときに仮定される Content-Type (デフォルトは<tt>"text/html"</tt>)。
I don't think this is clear expression. 
You don't need to stick to the original sentence in English :)

How about this?
`Content-Type がセットされていない場合に適用される (デフォルトは<tt>"text/html"</tt>)。`

2020-11-04 17:38 UTC, namusyaka commented on README.ja.md
> +    <tt>nil</tt> を設定するとすべてのレスポンスでデフォルトの Content-Type が設定されなくなる。
`<tt>default_content_type</tt> に <tt>nil</tt> を設定すると、すべてのレスポンスにデフォルトの Content-Type が設定されなくなる。`

2020-11-04 17:38 UTC, namusyaka commented on README.ja.md
> +    そうしないと、user-agenet はコンテンツを盗み見る必要がある。
`そうしなければ、user-agent がそれを推測しなければならなくなります。`
or `そうしなければ、user-agent が Content sniffing をしなければなりません。`

2020-11-04 17:38 UTC, namusyaka commented on README.ja.md
> +    (または、もし Rack::Protection::XSSHeader の <tt>nosniff</tt> が有効な場合、<tt>application/octet-stream</tt> と仮定される。)
`仮定します` or `決め込みます`

2021-06-25 10:39 UTC, decoch commented
@namusyaka  I'm sorry for the late reply.
Thanks for the review.
I fixed it.

2022-02-05 15:11 UTC, merged