Update "Getting Started" docs
sinatra/sinatra pull request #1764
Opened 2022-03-01 16:15 UTC by bnadlerjr

Ruby doesn't ship with Webrick anymore, so users will need to install their own webserver.

Fixes #1754

2022-03-01 20:23 UTC, dentarg requested changes
I think we should go with the more maintained web server Puma (default in Rails) (yes I see that thin has recently gained some traction, but nothing happened 2017-2020, thin also have the heavy and also not that well maintained dependency eventmachine)

Or just webrick

2022-03-01 23:58 UTC, jkowens commented
I think I would lean towards puma at this point too.

2022-03-02 01:10 UTC, bnadlerjr commented
Good point. I'll update it to Puma.

2022-03-03 19:33 UTC, bnadlerjr commented
Ok, I updated the PR to mention Puma instead of thin.

2022-03-03 20:04 UTC, jkowens commented
Cool, thanks for the update!

2022-03-03 20:04 UTC, merged