feature: add indifferent access support to `Hash#except`
sinatra/sinatra pull request #1940
Opened 2023-08-21 15:25 UTC by santiagorodriguez96

[It was added in Ruby 3.0](https://github.com/ruby/ruby/commit/82ca8c73034b0a522fd2970ea39edfcd801955fe) so it would be nice that calling except in a `Sinatra::IndifferntHash` supported the indifferent access that the latter provides – right now, calling `except(:a)` on `Sinatra::IndifferntHash[a: :a]` would not filter the `a` key.

This commits adds indifferent access support to except so that it will exclude the passed key independently if the key is passed as a `String` or `Symbol`.

2023-08-21 18:54 UTC, epergo requested changes

2023-08-21 18:54 UTC, epergo commented on lib/sinatra/indifferent_hash.rb
> +    end if Gem::Version.new(RUBY_VERSION) > Gem::Version.new("3.0")
```suggestion
    end if Gem::Version.new(RUBY_VERSION) >= Gem::Version.new("3.0")
```

2023-08-21 20:45 UTC, santiagorodriguez96 commented on lib/sinatra/indifferent_hash.rb
> +    end if Gem::Version.new(RUBY_VERSION) > Gem::Version.new("3.0")
My bad! Thanks 🙂

2023-08-22 09:41 UTC, olleolleolle approved these changes
I think this looks decent and would avoid some incompatibilities.

2023-08-22 15:29 UTC, merged